---
- name: Set vm.max_map_count in sysctl.conf
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: Set open files limit in sysctl.conf
  sysctl:
    name: fs.file-max
    value: 65536
    state: present

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Set soft memlock in /etc/security/limits.conf
  pam_limits:
    domain: opensearch
    limit_item: memlock
    limit_type: soft
    value: unlimited

- name: Set hard memlock in /etc/security/limits.conf
  pam_limits:
    domain: opensearch
    limit_item: memlock
    limit_type: hard
    value: unlimited
